image: $SKA_K8S_TOOLS_BUILD_DEPLOY  

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - lint
  - test
  - scan
  - build
  - publish
  - pages

include:
  # Pyton lint jobs
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/python-lint.gitlab-ci.yml'
  # Python test jobs
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/python-test.gitlab-ci.yml'
  # Python scan jobs
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/python-scan.gitlab-ci.yml'
  # Python build jobs
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/python-build.gitlab-ci.yml'
  # Python publish jobs
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/python-publish.gitlab-ci.yml'
  # Python jobs
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/python.gitlab-ci.yml'
  # Python release jobs
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/release.gitlab-ci.yml'
  # Badges from CI metrics
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/finaliser.gitlab-ci.yml'

  # Documentation jobs
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/docs.gitlab-ci.yml'


