default:
    image: python:3.6

stages:
    - test

before_script:
    - pip install --upgrade pip
    - pip install .

test:
    stage: test
    script:
        - pytest -m pipeline -c pytest.ini --ignore=src/ska_pss_protest/ --ignore=build
