image: $SKA_K8S_TOOLS_DOCKER_BUILDER_IMAGE

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - lint
  - test

lint:
  stage: lint
  image: python:3.6
  before_script:
    - pip install --upgrade pip
    - pip install .[dev]
  script:
    - isort --check-only --profile black --line-length 79  src/ tests/

include:
  # Python test jobs
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/python-test.gitlab-ci.yml'
